/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malinskiy_hcalc_Scarab */

#ifndef _Included_com_malinskiy_hcalculator_Scarab
#define _Included_com_malinskiy_hcalculator_Scarab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    generateKeys
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_malinskiy_hcalculator_Scarab_generateKeys
  (JNIEnv *, jclass);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    getPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinskiy_hcalculator_Scarab_getPublicKey
  (JNIEnv *, jclass);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    getSecretKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinskiy_hcalculator_Scarab_getSecretKey
  (JNIEnv *, jclass);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    encrypt
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinskiy_hcalculator_Scarab_encrypt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_malinskiy_hcalculator_Scarab_decrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    recrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinskiy_hcalculator_Scarab_recrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinskiy_hcalculator_Scarab_add
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    multiply
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinskiy_hcalculator_Scarab_multiply
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_malinskiy_hcalculator_Scarab_free
  (JNIEnv *, jclass);

/*
 * Class:     com_malinskiy_hcalc_Scarab
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_malinskiy_hcalculator_Scarab_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
