/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malinskiy_hcalculator_NativeHardware */

#ifndef _Included_com_malinskiy_hcalculator_NativeHardware
#define _Included_com_malinskiy_hcalculator_NativeHardware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malinskiy_hcalculator_NativeHardware
 * Method:    neonSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_malinskiy_hcalculator_NativeHardware_neonSupported
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
